### ISSUE TITLE
感谢大佬的开发的程序，建议借鉴一下tracert和OpenTrace

### ISSUE THREAD

**Issue by hsz0707** [Candinya/NyaTrace#11]
这是tracert的源代码，多线程追踪非常丝滑，但是不支持ipv6    https://github.com/makazeu/tracert
小有名气的OpenTrace 但是不支持多线程。https://github.com/Archeb/opentrace
这两个有些鸡肋的程序能结合一下就非常哇塞了。

**Comment by Candinya** [comment]
非常感谢您的建议，我们开发的时候也调研过相关的项目，情况是这样的：

- tracert 速度确实快，但它没有重试机制，并且不会解析主机名（这是一个非常耗时的请求，也是导致运行缓慢的原因之一），这意味着响应时丢包会导致结果不完整；
- OpenTrace 的底层是 NextTrace ，这是用 Go 写的，并且因为是裸套接字通讯而非系统底层调用所以存在权限问题

也因此，我们与上述项目的区别是：

- 相比于 tracert 我们引入了重试机制和主机名解析，所以会比较耗时，但我们认为这对于一个有效的追踪来说是必要的，如果只是想要拿到每一跳 IP 的话可以用一些已经成熟的工具，比如 mtr 来实现；
- 相比于 NextTrace 我们使用的是系统底层 API 调用，无需提权，但也因此存在系统相关的局限性（unix 系统上的 API 差距比较大，暂时我自己用得不多所以没怎么推进兼容）

所以非常感谢您的建议，但这些其实我们在开发的时候也都已经有相关的考虑了。
